repos:
  # mypy configuration
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.17.1'
    hooks:
    -   id: mypy
  # yapf configuration
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
    -   id: yapf
  # pylint configuration
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v2.5.3'
    hooks:
    -   id: pylint