repos:
  # mypy configuration
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: [mypy-extensions==0.4.3]
  # yapf configuration
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        additional_dependencies: [yapf==0.32.0]
  # pylint configuration
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.20.0
    hooks:
      - id: pylint
        additional_dependencies: [pylint==2.20.0, pylint-django==2.5.3]
  # flake8 configuration